version: '3.8'

services:
  ddc:
    image: dockerdiscordcontrol/dockerdiscordcontrol:latest
    container_name: ddc
    restart: unless-stopped
    
    # SICHERHEITS-EINSTELLUNGEN
    security_opt:
      - no-new-privileges:true
    
    # NUR localhost binding für Web UI
    ports:
      - "127.0.0.1:8374:9374"  # Web UI nur über localhost erreichbar
    
    # Volumes
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro  # Read-only Docker socket
      - ./config:/app/config
      - ./logs:/app/logs
    
    # Umgebungsvariablen
    environment:
      - TZ=Europe/Berlin
      - PUID=1000
      - PGID=1000
    
    # Netzwerk-Isolation
    networks:
      - ddc_internal

networks:
  ddc_internal:
    driver: bridge
    internal: false  # Set to true for complete isolation

# Für externen Zugriff nutze einen Reverse Proxy (nginx/traefik)
# oder SSH-Tunnel: ssh -L 8374:localhost:8374 user@server